# Generated by Django 3.2 on 2021-04-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalComps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chemical_element',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory', models.FloatField()),
                ('price', models.FloatField()),
                ('chemical_composition', models.ManyToManyField(related_name='commodities', to='OptimizerRestAPI.ChemicalComps')),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.AddField(
            model_name='chemicalcomps',
            name='chem_ele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_composition', to='OptimizerRestAPI.chemicalelement'),
        ),
    ]
