# Generated by Django 3.2 on 2021-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptimizerRestAPI', '0002_alter_chemicalcomps_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalcomps',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
